### ISSUE TITLE
Quests objectives only partly shown

### ISSUE THREAD

**Issue by BreakBB** [AeroScripts/QuestieDev#1071]
## Bug description

Reported on Discord.

On a Non-English client only some of the objectives are shown on the map. Restart and latest version didn't help.

An example is the quest [Unfinished Business](https://classic.wowhead.com/quest=6023/unfinished-business).
Only Cavalier Durgen is showing on the map.

The objective in the screenshot below says: "Huntman Regan slain", but it is shown on the location of Cavalier Durgen which has already been slain.

Moreover if the spawnDB gets changed from 
`{{11613,nil},{11611,nil},},nil,nil,nil,}` to 
`{{11611,nil},{11613,nil},},nil,nil,nil,}`

only "Huntsman Radley" is shown!

Tracker has the same issue.

Most likely related to #819 

## Screenshots

![WoWScrnShot_092019_160032](https://user-images.githubusercontent.com/33514570/65306255-48cc6980-db85-11e9-8b25-d9cff20f665e.jpg)

## Questie version

4.1.1

**Comment by BreakBB** [comment]
This is fixed with the latest commits on the master branch and will be included in the upcoming release of 4.1.2! Thanks for your patient on this.

**Comment by BreakBB** [comment]
To explain this a bit more:

Our fallback logic for missing translations had a problem and therefore we didn't match the objective data correctly for each mob.
So every quest which had more than 1 objective showed all objectives of the first mob listed in our database. This broke the tooltips on the mob itself and the drawing of the objective icons on the map as well.

**Comment by BreakBB** [comment]
This is fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2

Please try that version and let us know if there still is an issue

**Comment by Eveigh** [comment]
the issue is still there. for example https://classic.wowhead.com/quest=49/sweet-amber have only one point on map insteed of tree
![image](https://user-images.githubusercontent.com/40161800/65981481-e119f680-e481-11e9-958d-b7d3ce592bb0.png)
4.1.1 with fix from #1099 work better. In 4.1.2 this fix does not work.

**Comment by BreakBB** [comment]
@Eveigh I am sorry to hear the fix isn't working for you as expected. The problem of the "fix" that is suggested in #1099 is that it relies on the order of objectives from the DB. If we do this we'll break other things, so we have to find another solution

**Comment by Eveigh** [comment]
Yes. I noticed  this fix not workig in all cases. So i watching this issue.
Can i privide some additional information to help?

**Comment by BreakBB** [comment]
@Eveigh Since I can't reproduce this issue: Could you try to edit line 880 in QuestieQuest.lua from `if Quest.Objectives[objectiveIndex] == nil then` to  `if true then` and report if this helps?

**Comment by Eveigh** [comment]
no this is not work for me

**Comment by Eveigh** [comment]
@BreakBB I tested out case with kiling mobs and it works in 4.1.2 as indeded even without that modification. So problem is for loot something only.

**Comment by BreakBB** [comment]
Fixed with 7eb8fc8b8468634cf58aa85683be4f676aed6752

We forgot to include the newly added item translations for most languages and therefore the tooltips and icons weren't working. Keep an eye out for the upcoming release!

**Comment by BreakBB** [comment]
v4.2.0 is out https://github.com/AeroScripts/QuestieDev/releases/tag/v4.2.0

**Comment by BreakBB** [comment]
With the latest reports it seems this issue still exists and now affects English clients as well.

We're currently rewriting our code to determine the objectives of a quest and how we match the finding on our data. You can expect a fix on this with the next release.

**Comment by maxtest404** [comment]
In v4.3.0 this issue fix or not ?

**Comment by Muehe** [comment]
@maxtest404 Yes, objectives should be working fine now in all languages that have the data. Please let us know if you notice anything broken.

**Comment by wow-classic** [comment]
Version: 4.3.0 0 37acad5
Quest: More Wastewander Justice
Link: https://classic.wowhead.com/quest=1691
Russian version WoW
![Questie - 1](https://user-images.githubusercontent.com/55049724/67162453-c0e8a380-f36c-11e9-97be-25069785d6b4.png)

**Comment by wow-classic** [comment]
Version: 4.3.0 0 37acad5
Quest: The Bloodsail Buccaneers
Link: https://classic.wowhead.com/quest=608
Russian version WoW
![Questie - 2](https://user-images.githubusercontent.com/55049724/67162642-8849c980-f36e-11e9-9361-2627f94057d9.png)

**Comment by Eveigh** [comment]
"/reload ui" helps for me with same problem

**Comment by wow-classic** [comment]
> /reload ui

It seems to work. Thanks.

**Comment by Eveigh** [comment]
quest All Along the Watchtowers https://classic.wowhead.com/quest=5097
![image](https://user-images.githubusercontent.com/40161800/67552326-850a6100-f713-11e9-956b-80040e61206d.png)

i checked DB and spawns 10902-10905 have different point. so i think it is related to this issue. 
reload ui not helpes
Version: 5.0.1 2 e2e80b7

**Comment by Eveigh** [comment]
I believe that this is because of the goal of “marking” rather than “killing”

**Comment by AeroScripts** [comment]
The data should continue to improve over time but its a tough situation, any error in NPC names can cause this. Closing this for now
