### ISSUE TITLE
Faded Sell Prices on Items

### ISSUE THREAD

**Issue by vdm104** [AeroScripts/QuestieDev#128]
Mousing over Questie notes on the minimap or map causes item's sell prices to be faded out at vendors until the game is reloaded.

![ss 2015-06-25 at 09 17 33](https://cloud.githubusercontent.com/assets/13049817/8355083/0b86888c-1b1b-11e5-99c6-5d97cc4ed591.jpg)

**Comment by AeroScripts** [comment]
Still happens at least on flight path prices, apparently the fix didn't work across the board.

**Comment by Logonz** [comment]
Fix this by saving the layer value on the MAP tooltip code and reset it
each time you exit, should fix it, the reason this happens is because i
change the draw layer of "gametooltip" to have it over the Icons and over
the map as the map has a really high draw layer.

2015-08-21 9:13 GMT+02:00 AeroScripts <notifications@github.com>:

**Comment by Schaka** [comment]
Fixed in https://github.com/AeroScripts/QuestieDev/commit/f2caac2278c59c753f4ae19aa9e6751594a3fba4

**Comment by n0rc** [comment]
Unfortunately, this is not fixed. I still get this error with v3.68 and no other addons loaded.

**Comment by Dyaxler** [comment]
Noted. I'll look at the "MouseOnExit" code tonight see if Logonz code is still intact.

**Comment by n0rc** [comment]
Thanks! Just to clarify: This happens with item prices also, not just with the flight master map.

**Comment by Dyaxler** [comment]
What Logonz is saying is that when ever you hover over any Questie icon that is on a map, it changes the Frame Strata for the tooltip and it's not being reset back to the Blizzard default. Thus when you hover over another item that has a tool tip it looks "grey'd" out because it's at a different Frame Strata then it should be. I know what's he's talking about. :) I'll find it and fix it unless it's something else entirely.

I've actually seen both issues. At the Flight Master Map and when selling off Grey items to a vendor.

**Comment by n0rc** [comment]
Ah, I see. I mixed that up with #146 where the flight master bug is mentioned. Currently I can observe both bugs, too. Thanks for looking into it!

**Comment by Dyaxler** [comment]
OK, found it... I hope. I was able to repro the bug but after what I think will fix it was applied I wasn't able to get it to repro anymore.

I'll check this fix in tonight.

**Comment by Dyaxler** [comment]
This has been fixed in the latest release - Hotfix:
https://github.com/AeroScripts/QuestieDev/releases/latest
