### ISSUE TITLE
[3.0] Problem Rejold's New Brew in Kharanos in Dun Morogh

### ISSUE THREAD

**Issue by deeredman1991** [AeroScripts/QuestieDev#164]
Rejold's New Brew is not available until level 10 but I can see it on my map at level 9. Not a BIG deal but it is a minor bug I figured you guys should know about.

**Comment by Muehe** [comment]
Thanks for the report but I think this quest is available at level 8:

https://vanilla-twinhead.twinstar.cz/?quest=415
http://db.vanillagaming.org/?quest=415
http://wowwiki.wikia.com/wiki/Quest:Rejold's_New_Brew?oldid=818638

Which server did you test this on?

**Comment by deeredman1991** [comment]
nostalrius

**Comment by deeredman1991** [comment]
So I think it's server side because I am level 10 now and still no quest

**Comment by Logonz** [comment]
The minlevel data etc is clientside, IF you can take the quest (aka the yellow !) is serverside, but the mapnotes come from our database data which currently has 
minLevel = 8(Marker shows up) Level = 10(Used for if the quest is gray(no xp) or not)

I will look into if my check level code is wrong, and see if this quest is triggered correctly at home, if it is i will close unforunatly we cant really do anything about this.

**Comment by Muehe** [comment]
@deeredman1991 As you can see in the Twinhead link above, this quest has two questgivers. Have you checked them both, and if not, would you mind doing so?

Also this quest requires https://vanilla-twinhead.twinstar.cz/?quest=315 to be completed first, maybe this is the problem here?

**Comment by Muehe** [comment]
@Logonz Just realised this, but vanillagaming doesn't seem to support multiple quest givers...

**Comment by Logonz** [comment]
First of all, yes it does ive seen it, second of all i use mangos DB to get questgivers and finishers :)

**Comment by Muehe** [comment]
Ah so the "quest" for the right values begins anew :smile: Thanks for letting me know, will check this for classicdb.

**Comment by Muehe** [comment]
@deeredman1991 Don't bother with further testing, just did this on my setup. Ran past it on the first char :smiley: This quest becomes available only as long as [The Perfect Stout](https://vanilla-twinhead.twinstar.cz/?quest=315) has been finished and [Shimmer Stout](https://vanilla-twinhead.twinstar.cz/?quest=413) hasn't been accepted yet. This is for chars who finish The Perfect Stout at level 6/7 so they can't accept Shimmer Stout yet and go back to Kharanos. Nice catch!

@Logonz The wrong display can be avoided by checking the NextQuestId column from DB.

**Comment by Logonz** [comment]
this... should be fixed? Cant really test it tho but the data seems correct...

**Comment by Muehe** [comment]
Problem persists, should I have deleted SavedVariables? The !DataStore_Quests.lua:

```lua
-- Char 1:
DB_SeenQuests = {
	[413] = 1,
	[315] = 1,
	[414] = 1,
}
-- Char 2:
DB_SeenQuests = {
	[315] = 1,
}
```

Both still see 415, only the second should. When the second char accepts 413, he shouldn't see 415 anymore but he still does.
