### ISSUE TITLE
Missing requirements for The Black Shield and Suspicious Hoofprints

### ISSUE THREAD

**Issue by Helveg** [AeroScripts/QuestieDev#1845]
## Description
Quest markers are showing up for `Suspicious Hoofprints` and `The Black Shield` before the required quests to start them have been completed. I had the quest `James Hyal` in my log, but not finished, and abandoned it. But Questie already showed the aforementioned quests, but I couldn't interact with the shield or prints yet. Then after completing many irrelevant quests and `James Hyal` (which I believe was the requirement) and `The Missing Diplomat` I could interact with the pieces.

## Wowhead link
https://classic.wowhead.com/quest=1284/suspicious-hoofprints
https://classic.wowhead.com/quest=1320/the-black-shield

## Questie version
v5.8, I already finished the quests now.

**Comment by Helveg** [comment]
@BreakBB what happened with the issue?

**Comment by BreakBB** [comment]
@Helveg I fixed this and the fix will be included in the next release.

**Comment by nickdotwav** [comment]
Not fixed unfortunately, it shows the quest is available to be accepted but I can't click on the hoofprints, badges, or shields.
