### ISSUE TITLE
Quest still shows completed even if there are not enough items in your inventory (several turn ins for the same kind of item)

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#2100]
## Bug description

There are several quests that need encrypted twilight texts (2 repeatable ones):
https://classic.wowhead.com/item=20404/encrypted-twilight-text#objective-of

When I turn in one, then the other still shows completed on the map, even if I don't have 10 texts in my inventory anymore.
If there is a way to update this on quest completion, then questie should do so :)

## Questie version

5.10.3

**Comment by BreakBB** [comment]
@Djfe I think this is a problem with the blizzard API. As with other quests and quest related events, sometime there are simply no events we can listen and react to.

Will keep this open and try to investigate as I also have some twilight texts :)

**Comment by AeroScripts** [comment]
I wonder if we can re-check all quest hashes on turn in without too much overhead, if we can it should solve this issue

**Comment by Gogo1951** [comment]
There would be no way to handle this. The quest is completed... you choose which ones you want to complete.

**Comment by Djfe** [comment]
I still don't get it. What does that have to do with anything?
Lots of quests in wow have pre quests and are only shown once the pre quests are completed.

For example: you don't see certain uldaman Quests on the map before you did the quests in Ironforge with that dude next to the church where the trainers are at.

**Comment by Djfe** [comment]
I'm at level 2 and the quest shows up on the map.

Not a level 60 or something.

**Comment by Djfe** [comment]
I just posted comments below this thinking it was another issue. Ups

**Comment by Djfe** [comment]
> you choose which ones you want to complete.

Well, yes. I think you might've misunderstood what this is about.
If I complete quest 1, then quest 2 still shows me the turn in npc on the map instead of which mobs to farm for them (objects like bags).

Why shouldn't there be a way to check quest b upon completing quest a and checking quest a upon completing quest b.
(I agree, it's a lot to check, if you're doing it for every quest turn-in and not for some exceptions)

**Comment by Djfe** [comment]
in the end this is fixed by a relog so not a biggie.
If you want to leave this as it is, then that's fine by me :)

**Comment by Gogo1951** [comment]
OK, fair. I'll add this to #2515 - nice to have if we have time before BC.
