### ISSUE TITLE
Corpse Arrow does not work if sent to a Spirit Healer far away from body

### ISSUE THREAD

**Issue by ThiconZ** [AeroScripts/QuestieDev#362]
When the player dies and is sent to a Spirit Healer that is a far distance from their body, such as dying in The Stockades and being placed at the Spirit Healer just outside Stormwind, the Corpse Arrow will point downwards with an incorrect yards count and no estimated time.

I have not tried just running a very far distance from my corpse to see if the issue happens from that as well.

Screenshot of the issue:
![image](https://cloud.githubusercontent.com/assets/6924950/22138726/0eb4a75a-deb0-11e6-9294-64595000e769.png)

**Comment by Dyaxler** [comment]
I'll have to try that... might be where it was placed in the "show arrow function".

Did you try the latest build I just checked in a few minutes ago?

**Comment by ThiconZ** [comment]
@Dyaxler I have not had a chance to recheck the changes in a Battleground.

**Comment by Dyaxler** [comment]
Hmmm... I'm not getting this issue. However, I've made improvements to the arrow since you reported the bug. I would manually installing Questie by downloading a ZIP of the whole repository. Although a ton of changes have been made since the last official release.

**Comment by Dyaxler** [comment]
Try this release please when you retest it.
https://github.com/AeroScripts/QuestieDev/releases/latest

My steps... walked into Stockades and committed suicide. Popped in Graveyard and arrow pointed to instance entrance 800+ yards away. I should have taken a screen shot.

**Comment by ThiconZ** [comment]
Issue still occurs in version 3.67:
![image](https://cloud.githubusercontent.com/assets/6924950/22168481/e9a90038-df3a-11e6-8bd7-ac97f25390be.png)

To reproduce consistently, I walked into Stockades and died at the spawn location of the first two mobs then released my spirit after waiting ~3 seconds.

**Comment by Dyaxler** [comment]
Look at your map... do you see a Tombstone on your world map?

**Comment by Dyaxler** [comment]
Run this from your chat line while dead:

`/dump GetCorpseMapPosition()`

**Comment by ThiconZ** [comment]
After dying in Stockades and releasing: 0.39646875858307. I'm not sure if it helps but the default minimap arrow and worldmap marker works just fine with pointing towards my corpse being in Stockades.

Since /dump is not a built-in command in vanilla and I can't find a version of DevTools that works with vanilla I added a command to Questie to do the same.

**Comment by Dyaxler** [comment]
My version works:
[DevTools.zip](https://github.com/AeroScripts/QuestieDev/files/720754/DevTools.zip)

**Comment by Dyaxler** [comment]
Soooooo... have you had a chance to see if this was fixed after all the changes you did to the CorpseArrow for BG checks?

**Comment by Dyaxler** [comment]
Mine works! :D

![image](https://cloud.githubusercontent.com/assets/17400948/22171381/73b81d4e-df41-11e6-9195-28f18076cba2.png)

**Comment by ThiconZ** [comment]
Still does not work, opening and closing the worldmap will fix the arrow though - which is odd. The first dump i chat is with the arrow broken and the second is after fixing it with the worldmap.

![image](https://cloud.githubusercontent.com/assets/6924950/22171391/fec5d052-df5a-11e6-91ac-5b78e74a7b57.png)

**Comment by Dyaxler** [comment]
So wait... it's broken I.E. graphics are screwed and your distance is zero? Then opening and closing the Worldmap fixes it?

**Comment by ThiconZ** [comment]
Correct, the graphics of it have it pointing straight down with distance of 0 and opening and closing the Worldmap will make it work correctly once again.

**Comment by Dyaxler** [comment]
Try this... instead of having this huge glob of a "back up function" keep the one in Questie.lua but replace the block in QuestieArrow.lua with this:

```
    if UnitIsDeadOrGhost("player") then
        Questie:OnUpdate(elapsed)
    end
```

**Comment by ThiconZ** [comment]
Well dying now creates multiple errors (there might be more than these three)
![image](https://cloud.githubusercontent.com/assets/6924950/22171808/817e039e-df64-11e6-8029-876b8fd1c2c3.png)

**Comment by Dyaxler** [comment]
That is super weird... try my file - I have all your fixes in it.
[QuestieArrow.txt](https://github.com/AeroScripts/QuestieDev/files/720893/QuestieArrow.txt)

**Comment by ThiconZ** [comment]
This is with the Questie.lua changes to remove the fallback code block.

**Comment by Dyaxler** [comment]
Nooo... wrong one. :)

**Comment by Dyaxler** [comment]
Here is my Questie.lua
[Questie.txt](https://github.com/AeroScripts/QuestieDev/files/720894/Questie.txt)

**Comment by ThiconZ** [comment]
That appears to have resolved the issue with that error.

**Comment by Dyaxler** [comment]
Please. As soon as it looks good to you I'll check it in and update the release.

**Comment by ThiconZ** [comment]
After testing it quite a bit more, seems it still has issues with instances and opening and closing the Worldmap appears to be the only work around for getting it to fix itself. Other than that being placed at a Spirit Healer very far away from your corpse seems to have it working correctly.

It's good enough to make a new release for but this issue still needs more investigating and work put into it to fully resolve this issue.

**Comment by ThiconZ** [comment]
Possibly a related issue, sometimes when I release to a Spirit Healer the arrow will be facing the wrong direction (it'll color correctly and give the correct distance, just be facing the opposite direction until I take a step). Perhaps some update needs to be forced once releasing has been finished?

**Comment by Dyaxler** [comment]
Please try this build:
[Questie-3.68.zip](https://github.com/AeroScripts/QuestieDev/files/721082/Questie-3.68.zip)

If it works for you then I'll check in my changes and do a Hotfix release.

**Comment by ThiconZ** [comment]
It seems like it may have fixed the incorrectly facing arrow issue - though I didn't die enough to truly thoroughly test it. It still did not fix the instance issue. Perhaps also of use, when I get within exactly 650 yards of where my corpse location should be it will fix itself. Not sure what triggers it to fix at that specific value as I've tried running to different locations and waiting over 10 minutes but those never triggered anything to have it fix itself.

**Comment by Muehe** [comment]
This one is weird. I can reproduce it most of the time (at least on the first death in stockades after starting the game client), however many things seem to fix the issue temporarily, like going further away than the graveyard is (went over 1 kyards), going to stockades using `.tele stockades`, etc. The "fix" or whatever will persist through relogs sometimes but upon the next restart of the game client the bug reappears. It seems noteworthy that walking into the ~650 yards range fixes arrow behaviour, but does not change the GetCorpseMapPosition() output.

**Comment by Muehe** [comment]
I think I figured out why walking into a certain range fixes the arrow. It happens when you walk into the map area of Stormwind (not the actual zone, but once you have Stormwind-map specific x and y coordinates between 0 and 100).

**Comment by Muehe** [comment]
Yeah, turns out the used zone is wrong. Use `GetCurrentMapZone()` before setting the arrow, problem solved. The first two commands are just after dying with the arrow bugged out showing 1 yard, the second two are after opening the map:


![questie_arrow](https://cloud.githubusercontent.com/assets/8838573/22176051/028d325a-e002-11e6-8630-38e525653c70.jpg)

This might indicate that the bug only happens for zones where the map area is shared with that of other zones.

**Comment by Muehe** [comment]
I have been playing around with the code a bit and it doesn't seem to be as easy as I thought, unless I am missing something obvious. Passing the return value of `GetCurrentMapZone()` to `SetCrazyArrow()` instead of the current player zone did not fix the issue.

**Comment by Dyaxler** [comment]
Yeah, this is totally weird. I must have a mod that you guys don't that "fixes" my issue or causes me to never see it. However, if what you're saying is true then I think we'll need to execute GetCurrentMapZone() more often to "force" the returned values to be constantly forced into the arrow. It's possible that something else might be changing the values.

I'm going to try and see if there is a way that I can set a "lastKnownPlayerZone" variable that I can call so that if a player dies and ends up in a different zone, the GetCorpseMapPosition() will have map coordinates of the zone the player died IN rather than the zone he ends up at. I wonder if while *in* the Stockades if GetCurrentMapZone() would give the proper zone ID that we need. If so then setting the event trigger PLAYER_DIES which fires right after you die, it'll get GetCorpseMapPosition() = lastKnownPlayerZone.

BRD, LBRS and UBRS also comes to mind where this might happen as well.

**Comment by Dyaxler** [comment]
Also... we need to be using Astrolabe:GetCurrentPlayerPosition() instead of GetCurrentMapZone().

**Comment by Dyaxler** [comment]
So here. Execution order:
1. Before entering Stockades
![image](https://cloud.githubusercontent.com/assets/17400948/22177187/f9e03208-dfcd-11e6-800e-3b57d3e59cb6.png)

2. After entering Stockades
![image](https://cloud.githubusercontent.com/assets/17400948/22177192/058b4ea8-dfce-11e6-9a7c-e9dcbe24f426.png)

3. After death before hitting release
![image](https://cloud.githubusercontent.com/assets/17400948/22177201/161a0b10-dfce-11e6-93e2-afdf5110a2d5.png)

4. After hitting release
![image](https://cloud.githubusercontent.com/assets/17400948/22177202/1ffcd6e4-dfce-11e6-861e-2061461abf67.png)

**Comment by ThiconZ** [comment]
If you create a lastKnownPlayerZone variable it may need to be a saved variable as the player can always log out of the game after releasing but not reviving then log back in.

**Comment by Dyaxler** [comment]
I have a fix in coming but in the case that you're describing - they wouldn't get an arrow at all. Now you're talking about an "edge case" and we simply can't account for everything. I'd rather not make it a character saved variable unless it's necessary.

**Comment by Muehe** [comment]
This happens for me:

1. After entering
2. After releasing (bugged)
3. After opening map

![questie_arrow2](https://cloud.githubusercontent.com/assets/8838573/22178541/40a17c7c-e039-11e6-9626-dc8e6d6e5b53.jpg)

As you can see the Astrolabe function seems to get it wrong for some reason.

**Comment by Dyaxler** [comment]
Yeah, I noticed that too... but again I have a fix I just finished testing. Try this build...
[Questie-3.68.zip](https://github.com/AeroScripts/QuestieDev/files/721588/Questie-3.68.zip)

**Comment by Dyaxler** [comment]
So in a nutshell...  Astrolabe will capture the data we need when the player dies (before releasing to a grave yard) - a sudo Corpse Marker instead of using Blizzards API (GetCorpseMapPosition). Then we're setting unique Vars to call later that checks to see if the Corpse Arrow can be shown. Since we're using unique Vars we don't have to worry about the Arrow showing an objectives data rather than our Corpse Arrow.

**Comment by ThiconZ** [comment]
@Dyaxler that version still fails to properly work:
![image](https://cloud.githubusercontent.com/assets/6924950/22178794/217c6c50-e00f-11e6-9263-6652494033eb.png)

**Comment by Dyaxler** [comment]
yeah... I was finally able to get my client into a broken state... with Muehe's help we figured it out. This build should work. :)
[Questie-3.68.zip](https://github.com/AeroScripts/QuestieDev/files/721617/Questie-3.68.zip)

**Comment by ThiconZ** [comment]
Can confirm that it is working correctly now.

**Comment by Dyaxler** [comment]
Awesome! :)

**Comment by Dyaxler** [comment]
This has been fixed in the latest release:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by ThiconZ** [comment]
It seems this issue may be back/not fully resolved. After dying in the middle of the Alterac Mountains once I released my Spirit into Hillsbrad Foothills (as Alliance, so Southshore) the arrow once again pointed down at 0yards to my corpse. This might have something to do with the new zone remembrance variable being added.
