### ISSUE TITLE
Return of the Ring Quest adds Horde instead of Alliance version.

### ISSUE THREAD

**Issue by Hiethen** [AeroScripts/QuestieDev#489]
http://db.vanillagaming.org/?quest=2947

**Comment by Muehe** [comment]
The issue here is not data missing but somehow the horde version of this quest (2949) gets added to the cache instead of the alliance version. I dug around a bit but I haven't found out why this is happening yet. It shouldn't be. From what I see required races get checked correctly in the `Questie:getQuestHash` function. Must be missing something...

**Comment by ZoeyZolotova** [comment]
The reason it's adding the wrong quest is that both quests have the same description. See similar issue I fixed with A Plague Upon Thee quests. https://github.com/AeroScripts/QuestieDev/commit/47f8b1bed7a52c250616b3e355251e8afe6b5425

A similar fix should work for this quest.

**Comment by Muehe** [comment]
I see. But simply doing this:

```diff
diff --git a/!Questie/Database/addendum.lua b/!Questie/Database/addendum.lua
index 9f20da4..d234f85 100644
--- a/!Questie/Database/addendum.lua
+++ b/!Questie/Database/addendum.lua
@@ -8516,8 +8516,8 @@ QuestieLevLookup = {
   [""]={0,12012296},
  },
  ["Return of the Ring"]={
-  ["You may either keep the ring, or you may find the person responsible for the imprint and engravings on the inside of the band."]={77,550038613},
-  ["You may either keep the ring, or you may find the person responsible for the imprint and engravings on the inside of the band."]={178,550039738},
+  ["You may either keep the ring, or you may find the person responsible for the imprint and engravings on the inside of the band. [1]"]={77,550038613},
+  ["You may either keep the ring, or you may find the person responsible for the imprint and engravings on the inside of the band. [2]"]={178,550039738},
  },
  ["The Ruins of Stardust"]={
   ["Bring 5 Handfuls of Stardust to Pelturas in Astranaar."]={77,4257535253},
```

did not solve the issue, Alliance players still get directed to the Horde finishing NPC. The two quests are both present in the `QuestieLevLookup` table after this change, but for some reason the race mask is still ignored, as before.

**Comment by BreakBB** [comment]
This should be solved with the new questDB
