### ISSUE TITLE
Not compatible with TipBuddy + minor issues with 1.1 alpha

### ISSUE THREAD

**Issue by MOUZU** [AeroScripts/QuestieDev#80]
Is there any possibility to make it compatible with TipBuddy?
"..\TipBuddy.lua:2576: attempt to concatenate local 'position' (a table value)"

the blizzard Tooltip is really bad anyways, I'd appreciate if there would be a way to use both addons but for leveling I suppose I have to turn TipBuddy off.

-- also there seems to be in 1.1 alpha some chat displays for dev reasons, which are spaming a lot.
mainly "UpdateQuestInZone" and "UPDATEFRAMEONTRACKER" but also on accepting quest some integer values.

besides that great work so far!

**Comment by Logonz** [comment]
Have had a lot of problems with the tooltip trying to hook it after all other addons do... I will download tipbuddy and look into it, see if i can do something about it.

**Comment by Logonz** [comment]
Also, we could always add a way to disable tooltip from questie for people who want to use other tooltips instead.

**Comment by MOUZU** [comment]
I didn't want to make a new issue because of this minor thing, but since 2.02 I'm getting "QuestieTracker.lua:107" attempt to perform arithmetic on local 'have' ( a nil value)" on my lvl 60 char, works fine for the low level char though

**Comment by AeroScripts** [comment]
The line 107 error and instance errors have been fixed in v2.0.7

**Comment by Jaquesante** [comment]
This bug is still active on minimap icon mouseover in Questie 3.1 with TipBuddy 2.22

Changing `if (position) then` to `if (position and type(position) ~= 'table') then` in line 2575 of TipBuddy.lua will fix this.
