### ISSUE TITLE
Deeprun Rat Roundup

### ISSUE THREAD

**Issue by samgc3** [AeroScripts/QuestieDev#883]
Questie states: [ERROR] [QuestieQuest]: There was an error populating objectives for Deeprun Rat Roundup 6661 1 Interface\AddOns\Questie\Modules\QuestieQuest.lua:630: bad argument #1 to 'pairs' (table expected, got nil)

[image](https://user-images.githubusercontent.com/11469130/64488367-c058db00-d20c-11e9-93ca-c0a3171b61c7.png)

Questie version 4.0.15

**Comment by BreakBB** [comment]
Please update to the latest release. This issue was fixed with v4.0.16 or .17 :+:1

**Comment by AeroScripts** [comment]
Actually only partially fixed, but there is already an issue for this. It can't show icons in instances but we might be able to improve things to at least show tooltips (it might already show tooltips in .18)

**Comment by BreakBB** [comment]
Oh my bad, sorry. Merging this with #837
